### ISSUE TITLE
Pack weaved_installer into my own .bin?

### ISSUE THREAD

**Issue by baggednismo** [weaved/installer#1]
Hey there, I need to modify the installer to automate a process and I wasnt sure off hand how you would go about packing the contents of the weaved_installer into a single .bin like you have under the installer/binaries/ directory.

Any help would be appreciated

**Comment by Digital-Larry** [comment]
We're no longer using that method, however maybe this tool will help you do what you want:

http://setup.orsoneye.com/SelfExtractingScriptGenerator.aspx
